name: Build and test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: |
          echo "${{ secrets.GCP_P12_KEYFILE }}" > aaa
          echo "${{ secrets.GCP_JSON_KEYFILE }}" > bbb
          ls -al
          cat aaa
          cat bbb
